# Generated by Django 3.0.7 on 2021-02-16 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Topic name'),
        ),
    ]
