# Generated by Django 3.0.7 on 2021-02-16 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0003_auto_20210216_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='urlname',
            new_name='url_name',
        ),
    ]
