# Generated by Django 3.0.7 on 2021-02-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_auto_20210216_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='url_name',
            field=models.SlugField(max_length=100, verbose_name='URLNAME'),
        ),
    ]
